# Generated by Django 4.0.6 on 2022-09-03 11:27

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=111)),
                ('email', models.EmailField(max_length=125)),
                ('message', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='catagory',
            name='image',
            field=models.ImageField(upload_to='catagory/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
